title: "idad-wind-home"
tagline: ""
description: "Blog of Idad Wind"
github_username: idadwind1
email: idadwind@gmail.com

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

header_pages:
  - index.md
  - cn.md
  - en.md

exclude:
  - assets/stickers/structure.py

# set the size of the text to 'large' or 'small', default is small
font-size: small

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
